# Generated by Django 2.0.3 on 2018-10-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('published_date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
