# Generated by Django 2.0.3 on 2018-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
