# Generated by Django 2.0.3 on 2018-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181020_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
